/**
 *  Filename:       retarget.c
 *  Platform(s):    STM32F401
 *  Project:
 *  Created:        May 26, 2023
 *  Description:    This file implements some low-level C library and console
 *                  UART functions.
 *
 *  Notes:          This module is specific to the STM32CubeMX and STM32CubeIDE
 *                  development environment.
 *                  The 'dedicated console UART' (example: huart2) was
 *                  generated by STM32CubeMX and is defined in main.c.
 *
 *  Author:         Andreas Isenegger
 *  Copyright:      2023, Bitcontrol GmbH, Switzerland.
 *                  All rights reserved.
 */

#include "retarget.h"

#include <stdio.h>
#include <stm32f4xx_hal.h>

extern UART_HandleTypeDef huart1;
static UART_HandleTypeDef* huart = &huart1; // Project specific, generated by STM32CubeMX

int __io_getchar(void)
{
    int ch;
    HAL_UART_Receive(huart, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

int __io_putchar(int ch)
{
    HAL_UART_Transmit(huart, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/*
 * Notes on the implementation:
 *
 * Using gets() would simplify reading from the console:
 *   <cstdio>::gets()
 *   char * gets ( char * str );
 *
 * Reads characters from the standard input (stdin) and stores them as a C
 * string into str until a newline character or the end-of-file is reached.
 * The newline character, if found, is not copied into str.
 *
 * Notice that gets() is quite different from fgets(): not only gets uses stdin
 * as source, but it doesn't include the ending newline character in the
 * resulting string and doesn't allow to specify a maximum size for str
 * (which can lead to buffer overflows).
 *
 * Therefore, the C standard (2011) has definitively removed this function from
 * its specification.
 *
 * Source: https://www.cplusplus.com/reference/cstdio/gets/
 *
 * For this reason it isn't used by this function (or any other source code
 * by Bitcontrol GmbH).
 */
int readConsoleInput(char* str, int bufLen)
{
    int ch;
    int idx = 0;
    if (bufLen > 1) // Space for at least 1 char and the '\0' char
    {
        /* Flush Rx register. */
        HAL_UART_Receive(huart, (uint8_t *)&ch, 1, 0); // 0: return immediately

        /* Read characters until EOF or newline character is detected. */
        while (idx < bufLen - 1) // -1: Leave space for '\0' character
        {
            ch = getchar();
            if (ch != EOF && ch != '\n')
            {
                str[idx++] = ch;
            }
            else
            {
                break;
            }
        }

        /* Terminate the string, return it's length excluding the '\0' char. */
        str[idx] = '\0';
        return idx;
    }
    return -1;
}

/*
 * Notes on the implementation:
 *
 * On success, a non-negative value is returned. On error, the function returns
 * EOF (typically -1) and sets the error indicator (ferror).
 *
 * Source: https://www.cplusplus.com/reference/cstdio/puts/
 */
int writeConsoleOutput(const char* str)
{
    return fputs(str, stdout);
}
